spring:
  config:
    activate:
      on-profile: prod

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/manageemployee-prod
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/manageemployee-dev
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 9090
  error:
    include-message: always


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/manageemployee-test
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true


server:
  port: 1010


